export const siteConfig = {
  name: "MEGWIN公式サイト",
  shortName: "MEGWIN",
  description:
    "YouTubeパイオニアMEGWINの公式サイト。次世代ライブ配信、DIYギミックを融合。YouTube/TikTok自動化、プチトマト・バジルの水耕栽培AI化など、\"自動化×配信\"の実験を日々公開中。",
  url: "https://megwin.com",
  ogImage: "/og-image",
  author: "MEGWIN",
  location: "八王子市",
  keywords: [
    "MEGWIN",
    "めぐうぃん",
    "水耕栽培",
    "ライブ配信",
    "DIYギミック",
    "ギミック",
    "プチトマト",
    "バジル",
    "自動化",
    "YouTube自動化",
    "TikTok自動化",
    "AI",
    "ギミックストリーム",
    "八王子",
  ],
  navigation: [
    { label: "トップ", href: "/" },
    { label: "栽培日記", href: "/diary" },
    { label: "About", href: "/about" },
    { label: "お問い合わせ", href: "/contact" },
  ],
  social: {
    youtube: "https://www.youtube.com/megwin",
    x: "https://x.com/megwintv",
    instagram: "https://www.instagram.com/megwintvmegwin/",
    facebook: "https://www.facebook.com/megwintvofficial/",
  },
} as const;
